### ISSUE TITLE
I cant find discord RPC.

### ISSUE THREAD

**Issue by DRNUMBER1** [moomooooo/postman#1]
I was searching discordRPC.java in the src but did not find can you tell me the path/name of the place here you have stored it.
Thanks in advance.

**Comment by moomooooo** [comment]
**api -> util -> misc -> Discord**, and **postman -> module -> modules -> client -> DiscordRichPresence** ... it uses external jars tho, ill send them to u over discord if you'd like. srgantmoomoo#1052
