### ISSUE TITLE
AutoCrystal Changes

### ISSUE THREAD

**Issue by linustouchtips** [moomooooo/postman#10]
1. remove cancel crystal, it's a placebo and does nothing for your ca. (if you don't believe me, setup a counter on the SPacketDestroyEntities event and count broken crystals, cancel crystal does not affect that in any way)
2. Implement an actual raytrace, the current one does not help with wall placements whatsoever and actually hurts wall placements on some servers
3. Implement an actual rotations system, overriding the packet send on CPacketPlayer bypasses no servers.
4. Make new CanPlaceCrystal methods as the current ones are pretty bad
5. The entire ca is basically just gamesense, I would invest some time in rewriting it since gamesense's ca rn isn't great

**Comment by moomooooo** [comment]
the only thing i directly used gamesense for were most of the utils, which do include things like canPlaceCrystals, and i plan on rewriting stuff like that. i tend to get a lot of complaints about the placement especially in chasing situations it seems, which does have a lot to do with stuff like canPlaceCrystal, and my utils in general, it's something im working on. Also, this is why i use cancelCrystal https://www.youtube.com/watch?v=rfhV-t2IkFc. obviously have to work on placing/breaking for proper multiplacing. thank u for the criticism, linus is cool person.

**Comment by linustouchtips** [comment]
the multiplacing is because of the canPlaceCrystal.

that video doesn't prove anything, the ca is going fast cause you have 20 ms (refer to my test)

**Comment by moomooooo** [comment]
i wasn't trying to prove anything with the video, i am aware of canPlaceCrystals involvement, "which does have a lot to do with stuff like canPlaceCrystal". i am simply showing why i currently use cancel crystal. i have not gotten around to completely fixing postmans ca, certain things have been changed and fixed but as of now that in particular has not been. thank u for ur critiquing, it does help, once i get around to rewriting the ca i may remove cancel crystal. i don't have a lot of time rn which rlly sucks when something like this is just starting to pick up, but im currently working on a lot of rewrites for this client, i almost just gave up on it with how much code isn't mine, but i realized the amount of support behind this project is pretty valuable and rare (for someone like me at least). thank u a lot for pointing out what u did, it will certainly be worked on when i have enough time, and i appreciate someone like you pointing out ways to fix it.

**Comment by linustouchtips** [comment]
sounds amazing man, can't wait 👍
