### ISSUE TITLE
make the ca "smart"

### ISSUE THREAD

**Issue by XdFag** [moomooooo/postman#19]
the ca isnt that smart

**Comment by moomooooo** [comment]
ummm... what?

**Comment by ChompChompDead** [comment]
ca got brains

**Comment by moomooooo** [comment]
> ca got brains

yess

**Comment by TechAle** [comment]
You asked the same thing on gamesense lol, are you making this issue every where? Come on kid, dont use the ca as an excuse because you are bad.

**Comment by DRNUMBER1** [comment]
cristal aura

**Comment by moomooooo** [comment]
> You asked the same thing on gamesense lol, are you making this issue every where? Come on kid, dont use the ca as an excuse because you are bad.

lmfao
